name: Test Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make install
      run: make install
    - name: make
      run: make
    - name: play
      run: ./jogo
    - name: make debug
      run: |
        make debug
        ./valgrind.sh || exit 0
    - name: make clean
      run: make clean
